apiVersion: v1
description: Creates ServiceMonitor CRD of coredns for Kubernetes which maintaining by Rancher 2.
engine: gotpl
maintainers:
- name: Rancher Labs Support
  email: support@rancher.com
name: exporter-coredns
version: 0.0.1

