apiVersion: v1
kind: Service
metadata:
  name: grafana-operated
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    release: {{ .Release.Name }}
  ports:
    - name: web
      port: 3000
      targetPort: web