{{- if .Values.enabled }}
{{- if .Values.enabledRBAC }}
{{- if .Values.enabledPSP }}
apiVersion: {{ template "rbac_api_version" . }}
kind: ClusterRole
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "app.psp.fullname" . }}
rules:
- apiGroups: 
  - {{ template "psp_api_group" . }}
  resources: 
  - 'podsecuritypolicies'
  verbs:     
  - 'use'
  resourceNames:
  - {{ template "app.fullname" . }}
{{- end }}
{{- end }}
{{- end }}
