apiVersion: cluster.cattle.io/v3
kind: MonitorMetric
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    level: cluster
    component: controllermanager
    metric: volumes-depth
  name: controllermanager-volumes-depth
  namespace: {{ .Values.namespace }}
spec:
  expression: sum(volumes_depth{instance=~"$InstanceName"}) by ($GroupBy)
  step: 10
  description: controllermanager volumes depth
  detailsGroupBy: instance
  legendFormat: "Volumes depth"
  detailsLegendFormat: "Volumes depth([[instance]])"
---
apiVersion: cluster.cattle.io/v3
kind: MonitorMetric
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    level: cluster
    component: controllermanager
    metric: deployment-depth
  name: controllermanager-deployment-depth
  namespace: {{ .Values.namespace }}
spec:
  expression: sum(deployment_depth{instance=~"$InstanceName"}) by ($GroupBy)
  step: 10
  description: controllermanager deployment adds
  detailsGroupBy: instance
  legendFormat: "Deployment depth"
  detailsLegendFormat: "Deployment depth([[instance]])"
---
apiVersion: cluster.cattle.io/v3
kind: MonitorMetric
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    level: cluster
    component: controllermanager
    metric: replicaset-depth
  name: controllermanager-replicaset-depth
  namespace: {{ .Values.namespace }}
spec:
  expression: sum(replicaset_depth{instance=~"$InstanceName"}) by ($GroupBy)
  step: 10
  description: controllermanager replicaset depth
  detailsGroupBy: instance
  legendFormat: "Replicaset depth"
  detailsLegendFormat: "Replicaset depth([[instance]])"
---
apiVersion: cluster.cattle.io/v3
kind: MonitorMetric
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    level: cluster
    component: controllermanager
    metric: service-depth
  name: controllermanager-service-depth
  namespace: {{ .Values.namespace }}
spec:
  expression: sum(service_depth{instance=~"$InstanceName"}) by ($GroupBy)
  step: 10
  description: controllermanager service depth
  detailsGroupBy: instance
  legendFormat: "Service depth"
  detailsLegendFormat: "Service depth([[instance]])"
---
apiVersion: cluster.cattle.io/v3
kind: MonitorMetric
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    level: cluster
    component: controllermanager
    metric: serviceaccount-depth
  name: controllermanager-serviceaccount-depth
  namespace: {{ .Values.namespace }}
spec:
  expression: sum(serviceaccount_depth{instance=~"$InstanceName"}) by ($GroupBy)
  step: 10
  description: controllermanager serviceaccount depth
  detailsGroupBy: instance
  legendFormat: "Serviceaccount depth"
  detailsLegendFormat: "Serviceaccount depth([[instance]])"
---
apiVersion: cluster.cattle.io/v3
kind: MonitorMetric
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    level: cluster
    component: controllermanager
    metric: endpoint-depth
  name: controllermanager-endpoint-depth
  namespace: {{ .Values.namespace }}
spec:
  expression: sum(endpoint_depth{instance=~"$InstanceName"}) by ($GroupBy)
  step: 10
  description: controllermanager endpoint depth
  detailsGroupBy: instance
  legendFormat: "Endpoint depth"
  detailsLegendFormat: "Endpoint depth([[instance]])"
---
apiVersion: cluster.cattle.io/v3
kind: MonitorMetric
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    level: cluster
    component: controllermanager
    metric: daemonset-depth
  name: controllermanager-daemonset-depth
  namespace: {{ .Values.namespace }}
spec:
  expression: sum(daemonset_depth{instance=~"$InstanceName"}) by ($GroupBy)
  step: 10
  description: controllermanager daemonset depth
  detailsGroupBy: instance
  legendFormat: "Daemonset depth"
  detailsLegendFormat: "Daemonset depth([[instance]])"
---

apiVersion: cluster.cattle.io/v3
kind: MonitorMetric
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    level: cluster
    component: controllermanager
    metric: deployment-depth
  name: controllermanager-deployment-depth
  namespace: {{ .Values.namespace }}
spec:
  expression: sum(deployment_depth{instance=~"$InstanceName"}) by ($GroupBy)
  step: 10
  description: controllermanager deployment depth
  detailsGroupBy: instance
  legendFormat: "Deployment depth"
  detailsLegendFormat: "Deployment depth([[instance]])"
---
apiVersion: cluster.cattle.io/v3
kind: MonitorMetric
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    level: cluster
    component: controllermanager
    metric: statefulset-depth
  name: controllermanager-statefulset-depth
  namespace: {{ .Values.namespace }}
spec:
  expression: sum(statefulset_depth{instance=~"$InstanceName"}) by ($GroupBy)
  step: 10
  description: controllermanager statefulset adds
  detailsGroupBy: instance
  legendFormat: "Statefulset depth"
  detailsLegendFormat: "Statefulset depth([[instance]])" 