apiVersion: cluster.cattle.io/v3
kind: MonitorMetric
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    level: project
    component: workload
    metric: disk-io-writes-bytes-sum-rate
    graph: disk-io
  name: workload-disk-io-writes-bytes-sum-rate
  namespace: {{ .Values.namespace }}
spec:
  expression: sum(rate(container_fs_writes_bytes_total{namespace="$Namespace",pod_name=~"$InstanceName"}[5m])) by ($GroupBy)  * 8 / 1024
  step: 10
  description: workload disk io writes bytes sum rate
  detailsGroupBy: pod_name
  legendFormat: "Write"
  detailsLegendFormat: "Write([[pod_name]])"
---
apiVersion: cluster.cattle.io/v3
kind: MonitorMetric
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    level: project
    component: workload
    metric: disk-io-reads-bytes-sum-rate
    graph: disk-io
  name: workload-disk-io-reads-bytes-sum-rate
  namespace: {{ .Values.namespace }}
spec:
  expression: sum(rate(container_fs_reads_bytes_total{namespace="$Namespace",pod_name=~"$InstanceName"}[5m])) by ($GroupBy) * 8 / 1024
  step: 10
  description: workload disk io reads bytes sum rate
  detailsGroupBy: pod_name
  legendFormat: "Read"
  detailsLegendFormat: "Read([[pod_name]])"
---
apiVersion: cluster.cattle.io/v3
kind: MonitorMetric
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    level: project
    component: workload
    metric: fs-bytes-sum
  name: workload-fs-bytes-sum
  namespace: {{ .Values.namespace }}
spec:
  expression: sum(container_fs_usage_bytes{namespace="$Namespace", pod_name=~"$InstanceName"}) by ($GroupBy)
  step: 10
  description: workload fs bytes sum
  detailsGroupBy: pod_name
  legendFormat: "File usage"
  detailsLegendFormat: "pod_name]]"
---
apiVersion: cluster.cattle.io/v3
kind: MonitorMetric
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    level: project
    component: workload
    metric: network-transmit-packets-sum-rate
    graph: network-packet
  name: workload-network-transmit-packets-sum-rate
  namespace: {{ .Values.namespace }}
spec:
  expression: sum(rate(container_network_transmit_packets_total{namespace="$Namespace",pod_name=~"$InstanceName"}[5m])) by ($GroupBy)
  step: 10
  description: workload network transmit packets sum rate
  detailsGroupBy: pod_name
  legendFormat: "Transmit packets"
  detailsLegendFormat: "Transmit packets([[pod_name]])"
---
apiVersion: cluster.cattle.io/v3
kind: MonitorMetric
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    level: project
    component: workload
    metric: network-receive-packets-dropped-sum-rate
    graph: network-packet
  name: workload-network-receive-packets-dropped-sum-rate
  namespace: {{ .Values.namespace }}
spec:
  expression: sum(rate(container_network_receive_packets_dropped_total{namespace="$Namespace",pod_name=~"$InstanceName"}[5m])) by ($GroupBy)
  step: 10
  description: workload network receive packets dropped sum rate
  detailsGroupBy: pod_name
  legendFormat: "Receive packets dropped"
  detailsLegendFormat: "Receive packets dropped([[pod_name]])"
---
apiVersion: cluster.cattle.io/v3
kind: MonitorMetric
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    level: project
    component: workload
    metric: cpu-usage-seconds-sum-rate
    graph: container-cpu-usage
  name: workload-cpu-usage-seconds-sum-rate
  namespace: {{ .Values.namespace }}
spec:
  expression: sum(rate(container_cpu_usage_seconds_total{namespace="$Namespace",pod_name=~"$InstanceName"}[5m])) by ($GroupBy) 
  step: 10
  description: workload cpu usage seconds sum rate
  detailsGroupBy: pod_name
  legendFormat: "CPU usage seconds"
  detailsLegendFormat: "CPU usage seconds([[pod_name]])"
---
apiVersion: cluster.cattle.io/v3
kind: MonitorMetric
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    level: project
    component: workload
    metric: cpu-system-seconds-sum-rate
    graph: container-cpu-usage-details
  name: workload-cpu-system-seconds-sum-rate
  namespace: {{ .Values.namespace }}
spec:
  expression: sum(rate(container_cpu_system_seconds_total{namespace="$Namespace",pod_name=~"$InstanceName"}[5m])) by ($GroupBy)
  step: 10
  description: workload cpu system seconds sum rate
  detailsGroupBy: pod_name
  legendFormat: "CPU system seconds"
  detailsLegendFormat: "CPU system seconds([[pod_name]])"
---
apiVersion: cluster.cattle.io/v3
kind: MonitorMetric
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    level: project
    component: workload
    metric: network-receive-bytes-sum-rate
    graph: network-io
  name: workload-network-receive-bytes-sum-rate
  namespace: {{ .Values.namespace }}
spec:
  expression: sum(rate(container_network_receive_bytes_total{namespace="$Namespace",pod_name=~"$InstanceName"}[5m])) by ($GroupBy) * 8 / 1024
  step: 10
  description: workload network receive bytes sum rate
  detailsGroupBy: pod_name
  legendFormat: "Receive"
  detailsLegendFormat: "Receive([[pod_name]])"
---
apiVersion: cluster.cattle.io/v3
kind: MonitorMetric
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    level: project
    component: workload
    metric: network-receive-errors-sum-rate
    graph: network-packet
  name: workload-network-receive-errors-sum-rate
  namespace: {{ .Values.namespace }}
spec:
  expression: sum(rate(container_network_receive_errors_total{namespace="$Namespace",pod_name=~"$InstanceName"}[5m])) by ($GroupBy)
  step: 10
  description: workload network receive errors sum rate
  detailsGroupBy: pod_name
  legendFormat: "Receive errors"
  detailsLegendFormat: "Receive errors([[pod_name]])"
---
apiVersion: cluster.cattle.io/v3
kind: MonitorMetric
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    level: project
    component: workload
    metric: network-receive-packets-sum-rate
    graph: network-packet
  name: workload-network-receive-packets-sum-rate
  namespace: {{ .Values.namespace }}
spec:
  expression: sum(rate(container_network_receive_packets_total{namespace="$Namespace",pod_name=~"$InstanceName"}[5m])) by ($GroupBy)
  step: 10
  description: workload network receive packets sum rate
  detailsGroupBy: pod_name
  legendFormat: "Receive packets"
  detailsLegendFormat: "Receive packets([[pod_name]])"
---
apiVersion: cluster.cattle.io/v3
kind: MonitorMetric
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    level: project
    component: workload
    metric: memory-usage-bytes-sum
  name: workload-memory-usage-bytes-sum
  namespace: {{ .Values.namespace }}
spec:
  expression: sum(container_memory_working_set_bytes{name!~"POD", namespace="$Namespace",pod_name=~"$InstanceName"}) by ($GroupBy)
  step: 10
  description: workload memory usage bytes sum
  detailsGroupBy: pod_name
  legendFormat: "Memory"
  detailsLegendFormat: "[[pod_name]]"
---
apiVersion: cluster.cattle.io/v3
kind: MonitorMetric
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    level: project
    component: workload
    metric: memory-usage-percent
  name: workload-memory-usage-percent
  namespace: {{ .Values.namespace }}
spec:
  expression: sum(container_memory_working_set_bytes{namespace="$Namespace", pod_name=~"$InstanceName"}) by ($GroupBy) / sum(label_join(kube_pod_container_resource_limits_memory_bytes{namespace="$Namespace", pod=~"$InstanceName"},"pod_name", "", "pod")) by ($GroupBy)
  step: 10
  description: workload memory usage percent
  detailsGroupBy: pod_name
  legendFormat: "Usage percent"
  detailsLegendFormat: "Usage percent([[pod_name]])"
---
apiVersion: cluster.cattle.io/v3
kind: MonitorMetric
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    level: project
    component: workload
    metric: network-transmit-bytes-sum-rate
    graph: network-io
  name: workload-network-transmit-bytes-sum-rate
  namespace: {{ .Values.namespace }}
spec:
  expression: sum(rate(container_network_transmit_bytes_total{namespace="$Namespace",pod_name=~"$InstanceName"}[5m])) by ($GroupBy) * 8 / 1024
  step: 10
  description: workload network transmit bytes sum rate
  detailsGroupBy: pod_name
  legendFormat: "Transmit"
  detailsLegendFormat: "Transmit([[pod_name]])"
---
apiVersion: cluster.cattle.io/v3
kind: MonitorMetric
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    level: project
    component: workload
    metric: network-transmit-errors-sum-rate
    graph: network-packet
  name: workload-network-transmit-errors-sum-rate
  namespace: {{ .Values.namespace }}
spec:
  expression: sum(rate(container_network_transmit_errors_total{namespace="$Namespace",pod_name=~"$InstanceName"}[5m])) by ($GroupBy)
  step: 10
  description: workload network transmit errors sum rate
  detailsGroupBy: pod_name
  legendFormat: "Receive transmit errors"
  detailsLegendFormat: "Transmit errors([[pod_name]])"
---
apiVersion: cluster.cattle.io/v3
kind: MonitorMetric
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    level: project
    component: workload
    metric: network-transmit-packets-dropped-sum-rate
    graph: network-packet
  name: workload-network-transmit-packets-dropped-sum-rate
  namespace: {{ .Values.namespace }}
spec:
  expression: sum(rate(container_network_transmit_packets_dropped_total{namespace="$Namespace",pod_name=~"$InstanceName"}[5m])) by ($GroupBy)
  step: 10
  description: workload network transmit packets dropped sum rate
  detailsGroupBy: pod_name
  legendFormat: "Transmit packets dropped"
  detailsLegendFormat: "Transmit packets dropped([[pod_name]])"
---
apiVersion: cluster.cattle.io/v3
kind: MonitorMetric
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    level: project
    component: workload
    metric: cpu-user-seconds-sum-rate
    graph: container-cpu-usage-details
  name: workload-cpu-user-seconds-sum-rate
  namespace: {{ .Values.namespace }}
spec:
  expression: sum(rate(container_cpu_user_seconds_total{namespace="$Namespace",pod_name=~"$InstanceName"}[5m])) by ($GroupBy)
  step: 10
  description: workload cpu user seconds sum rate
  detailsGroupBy: pod_name
  legendFormat: "CPU user seconds"
  detailsLegendFormat: "CPU user seconds([[pod_name]])"
---
apiVersion: cluster.cattle.io/v3
kind: MonitorMetric
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    level: project
    component: workload
    metric: cpu-cfs-throttled-seconds-sum-rate
  name: workload-cpu-cfs-throttled-seconds-sum-rate
  namespace: {{ .Values.namespace }}
spec:
  expression: sum(rate(container_cpu_cfs_throttled_seconds_total{namespace="$Namespace",pod_name=~"$InstanceName"}[5m])) by ($GroupBy)
  step: 10
  description: workload cpu cfs throttled seconds sum rate
  detailsGroupBy: pod_name
  legendFormat: "CPU cfs throttled"
  detailsLegendFormat: "CPU cfs throttled([[pod_name]])"