apiVersion: cluster.cattle.io/v3
kind: MonitorMetric
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    level: cluster
    component: apiserver
    metric: request-latency-milliseconds-avg
  name: apiserver-request-latency-milliseconds-avg
  namespace: {{ .Values.namespace }}
spec:
  expression: avg(apiserver_request_latencies_sum / apiserver_request_latencies_count) by ($GroupBy) /1e+06  
  step: 10
  description: apiserver request latency milliseconds avg
  groupBy: instance
  detailsGroupBy: instance, verb
  legendFormat: "[[instance]]"  
  detailsLegendFormat: "[[verb]]([[instance]])"
---
apiVersion: cluster.cattle.io/v3
kind: MonitorMetric
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    level: cluster
    component: apiserver
    metric: request-count-sum-rate
  name: apiserver-request-count-sum-rate
  namespace: {{ .Values.namespace }}
spec:
  expression: sum(rate(apiserver_request_count{instance=~"$InstanceName"}[5m])) by ($GroupBy)
  step: 10
  description: apiserver request count sum rate
  groupBy: instance
  detailsGroupBy: instance, code
  legendFormat: "[[instance]]"
  detailsLegendFormat: "[[code]]([[instance]])"