apiVersion: management.cattle.io/v3
kind: ProjectMonitorGraph
metadata:
  labels:
    app: metric-expression
    namespace: cattle-prometheus
    source: rancher-monitoring
    level: project
    component: container
  name: container-cpu-usage
  namespace: cattle-prometheus
spec:
  enable: true
  priority: 800
  title: container-cpu-usage
  thresholds: 10
  metricsSelector:
    details: "false"
    component: container
    graph: container-cpu-usage
  detailsMetricsSelector:
    details: "true"
    component: container
    graph: container-cpu-usage-details
  xAxis:
    show: true
  yAxis:
    show: true
    unit: mcpu
---
apiVersion: management.cattle.io/v3
kind: ProjectMonitorGraph
metadata:
  labels:
    app: metric-expression
    namespace: cattle-prometheus
    source: rancher-monitoring
    level: project
    component: container
  name: container-memory-usage-bytes-sum
spec:
  enable: true
  priority: 801
  title: container-memory-usage-bytes-sum
  thresholds: 10
  metricsSelector:
    details: "false"
    component: container
    metric: memory-usage-bytes-sum
  detailsMetricsSelector:
    details: "true"
    component: container
    metric: memory-usage-bytes-sum
  xAxis:
    show: true
  yAxis:
    show: true
    unit: byte
---
apiVersion: management.cattle.io/v3
kind: ProjectMonitorGraph
metadata:
  labels:
    app: metric-expression
    namespace: cattle-prometheus
    source: rancher-monitoring
    level: project
    component: container
  name: container-network-io
spec:
  enable: true
  priority: 802
  title: container-network-io
  thresholds: 10
  metricsSelector:
    details: "false"
    component: container
    graph: network-io
  detailsMetricsSelector:
    details: "true"
    component: container
    graph: network-io
  xAxis:
    show: true
  yAxis:
    show: true
    unit: kbps
---
apiVersion: management.cattle.io/v3
kind: ProjectMonitorGraph
metadata:
  labels:
    app: metric-expression
    namespace: cattle-prometheus
    source: rancher-monitoring
    level: project
    component: container
  name: container-network-packet
spec:
  enable: true
  priority: 803
  title: container-network-packet
  thresholds: 10
  metricsSelector:
    details: "false"
    component: container
    graph: network-packet
  detailsMetricsSelector:
    details: "true"
    component: container
    graph: network-packet
  xAxis:
    show: true
  yAxis:
    show: true
    unit: pps
---
apiVersion: management.cattle.io/v3
kind: ProjectMonitorGraph
metadata:
  labels:
    app: metric-expression
    namespace: cattle-prometheus
    source: rancher-monitoring
    level: project
    component: container
  name: container-disk-io
spec:
  enable: true
  priority: 804
  title: container-disk-io
  thresholds: 10
  metricsSelector:
    details: "false"
    component: container
    graph: disk-io
  detailsMetricsSelector:
    details: "true"
    component: container
    graph: disk-io
  xAxis:
    show: true
  yAxis:
    show: true
    unit: kbps