apiVersion: management.cattle.io/v3
kind: ProjectMonitorGraph
metadata:
  labels:
    app: metric-expression
    namespace: cattle-prometheus
    source: rancher-monitoring
    level: project
    component: workload
  name: workload-cpu-usage
  namespace: cattle-prometheus
spec:
  enable: true
  priority: 600
  title: workload-cpu-usage
  thresholds: 10
  metricsSelector:
    details: "false"
    component: workload
    graph: container-cpu-usage
  detailsMetailsMetricsSelector:
    details: "true"
    component: pod
    graph: container-cpu-usage-details
  xAxis:
    show: true
  yAxis:
    show: true
    unit: mcpu
---
apiVersion: management.cattle.io/v3
kind: ProjectMonitorGraph
metadata:
  labels:
    app: metric-expression
    namespace: cattle-prometheus
    source: rancher-monitoring
    level: project
    component: workload
  name: workload-memory-usage-bytes-sum
spec:
  enable: true
  priority: 601
  title: workload-memory-usage-bytes-sum
  thresholds: 10
  metricsSelector:
    details: "false"
    component: workload
    metric: memory-usage-bytes-sum
  detailsMetricsSelector:
    details: "true"
    component: workload
    metric: memory-usage-bytes-sum
  xAxis:
    show: true
  yAxis:
    show: true
    unit: byte
---
apiVersion: management.cattle.io/v3
kind: ProjectMonitorGraph
metadata:
  labels:
    app: metric-expression
    namespace: cattle-prometheus
    source: rancher-monitoring
    level: project
    component: workload
  name: workload-network-io
spec:
  enable: true
  priority: 602
  title: workload-network-io
  thresholds: 10
  metricsSelector:
    details: "false"
    component: workload
    graph: network-io
  detailsMetricsSelector:
    details: "true"
    component: workload
    graph: network-io
  xAxis:
    show: true
  yAxis:
    show: true
    unit: kbps
---
apiVersion: management.cattle.io/v3
kind: ProjectMonitorGraph
metadata:
  labels:
    app: metric-expression
    namespace: cattle-prometheus
    source: rancher-monitoring
    level: project
    component: workload
  name: workload-network-packet
spec:
  enable: true
  priority: 603
  title: workload-network-packet
  thresholds: 10
  metricsSelector:
    details: "false"
    component: workload
    graph: network-packet
  detailsMetricsSelector:
    details: "true"
    component: workload
    graph: network-packet
  xAxis:
    show: true
  yAxis:
    show: true
    unit: pps
---
apiVersion: management.cattle.io/v3
kind: ProjectMonitorGraph
metadata:
  labels:
    app: metric-expression
    namespace: cattle-prometheus
    source: rancher-monitoring
    level: project
    component: workload
  name: workload-disk-io
spec:
  enable: true
  priority: 604
  title: workload-disk-io
  thresholds: 10
  metricsSelector:
    details: "false"
    component: workload
    graph: disk-io
  detailsMetricsSelector:
    details: "true"
    component: workload
    graph: disk-io
  xAxis:
    show: true
  yAxis:
    show: true
    unit: kbps