apiVersion: cluster.cattle.io/v3
kind: MonitorGraph
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    level: cluster
    component: scheduler
    cluster-graph: kube-component
  name: scheduler-e-2-e-scheduling-latency-seconds-quantile
  namespace: {{ .Values.namespace }}
spec:
  enable: true
  priority: 320
  title: scheduler-e-2-e-scheduling-latency-seconds-quantile
  thresholds: 10
  metricsSelector:
    component: scheduler
    metric: e-2-e-scheduling-latency-seconds-quantile
  xAxis:
    show: true
  yAxis:
    show: true
    unit: seconds
---
apiVersion: cluster.cattle.io/v3
kind: MonitorGraph
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    level: cluster
    component: scheduler
    cluster-graph: kube-component
  name: scheduler-total-preemption-attempts
spec:
  enable: true
  priority: 321
  title: scheduler-total-preemption-attempts
  thresholds: 10
  metricsSelector:
    component: scheduler
    metric: total-preemption-attempts
  xAxis:
    show: true
  yAxis:
    show: true
    unit: number
---
apiVersion: cluster.cattle.io/v3
kind: MonitorGraph
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    level: cluster
    component: scheduler
    cluster-graph: kube-component
  name: scheduler-pod-unscheduler
spec:
  enable: true
  priority: 322
  title: scheduler-pod-unscheduler
  thresholds: 10
  metricsSelector:
    component: scheduler
    metric: pod-unscheduler
  xAxis:
    show: true
  yAxis:
    show: true
    unit: number